version: "3.7"

services:
  node-red:
    image: callumb/node-red-preinstall:latest
    environment:
      - TZ=Australia/Melbourne
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./data/node-red:/data
  mqtt:
    image: eclipse-mosquitto:latest
    environment:
      - TZ=Australia/Melbourne
    networks:
      - node-red-net
    ports:
      - "1883:1883"
    volumes:
      - ./data/mosquitto:/mosquitto
  face-detection:
    image: callumb/robot-face-detection:latest
    devices:
      - /dev/video0:/dev/video0
    env_file:
      - .env
    networks:
      - node-red-net

networks:
  node-red-net: